namespace SpiceNet.Protocol;

public enum SpiceMouseButton
{
    SPICE_MOUSE_BUTTON_INVALID,
    SPICE_MOUSE_BUTTON_LEFT,
    SPICE_MOUSE_BUTTON_MIDDLE,
    SPICE_MOUSE_BUTTON_RIGHT,
    SPICE_MOUSE_BUTTON_UP,
    SPICE_MOUSE_BUTTON_DOWN,
    SPICE_MOUSE_BUTTON_SIDE,
    SPICE_MOUSE_BUTTON_EXTRA,
    SPICE_MOUSE_BUTTON_ENUM_END,
}
