namespace SpiceNet.Protocol;

public enum SpiceImageCompression
{
    SPICE_IMAGE_COMPRESSION_INVALID,
    SPICE_IMAGE_COMPRESSION_OFF,
    SPICE_IMAGE_COMPRESSION_AUTO_GLZ,
    SPICE_IMAGE_COMPRESSION_AUTO_LZ,
    SPICE_IMAGE_COMPRESSION_QUIC,
    SPICE_IMAGE_COMPRESSION_GLZ,
    SPICE_IMAGE_COMPRESSION_LZ,
    SPICE_IMAGE_COMPRESSION_LZ4,
    SPICE_IMAGE_COMPRESSION_ENUM_END,
}
