namespace SpiceNet.Protocol;

public enum SpiceVideoCodecType
{
    SPICE_VIDEO_CODEC_TYPE_MJPEG = 1,
    SPICE_VIDEO_CODEC_TYPE_VP8,
    SPICE_VIDEO_CODEC_TYPE_H264,
    SPICE_VIDEO_CODEC_TYPE_VP9,
    SPICE_VIDEO_CODEC_TYPE_H265,
    SPICE_VIDEO_CODEC_TYPE_ENUM_END,
}
