namespace SpiceNet.Protocol;

public enum SpiceNotifyVisibility : uint
{
    SPICE_NOTIFY_VISIBILITY_LOW,
    SPICE_NOTIFY_VISIBILITY_MEDIUM,
    SPICE_NOTIFY_VISIBILITY_HIGH,
    SPICE_NOTIFY_VISIBILITY_ENUM_END,
}
